FROM golang:1.23-alpine

WORKDIR /app

# Install Chrome and its dependencies
RUN apk add --no-cache \
    chromium \
    chromium-chromedriver \
    gcc \
    musl-dev \
    # Chrome dependencies
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    nodejs \
    yarn

# Set Chrome binary location
ENV CHROME_BIN=/usr/bin/chromium-browser
ENV CHROME_PATH=/usr/lib/chromium/

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["go", "run", "cmd/api/main.go"] 